on:
  push:
    branches:
      - actionsTest
  workflow_dispatch:

jobs:
  updateMinorVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Increment Minor Version
        id: calc
        uses: yk1028/yk1028-calc-action@v0.0.2
        with:
          x: ${{ vars.MINOR }}
          y: 1
      - uses: actions/checkout@v3
      - run: |
          gh variable set MINOR --body "${{steps.calc.outputs.plus}}"
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
  GET_MINOR_VERSION:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"
      - uses: actions/checkout@v3
      - run: |
          gh variable get MINOR
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
