on:
  push:
    branches:
      - actionsTest
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh variable list
          gh variable set MAJOR --body "Set from workflow second time"
          gh variable list
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
