on:
  push:
    branches:
      - actionsTest
  workflow_dispatch:

jobs:
  updateMinorVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Increment Minor Version
        id: calc
        uses: yk1028/yk1028-calc-action@v0.0.2
        with:
          x: ${{ vars.MINOR }}
          y: 1
      - uses: actions/checkout@v3
      - run: |
          gh variable set MINOR --body "${{steps.calc.outputs.plus}}"
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Get Minor Version
        env:
          MINOR: ${{ vars.MINOR }}
        run: |
          echo "${{env.MINOR}}"
      - name: Get Minor Version
        env:
          MINOR: ${{ vars.MINOR }}
        run: |
          echo "${{env.MINOR}}"
       - name: Sleep for 30 seconds
         uses: jakejarvis/wait-action@master
         with:
          time: '30s'
      - name: Get Minor Version
        env:
          MINOR: ${{ vars.MINOR }}
        run: |
          echo "${{env.MINOR}}"
