name: UI Status Check 🤖👽

on:
  push:
    branches:
      - "!master"
      - "**"
jobs:
  # This workflow contains a single job called "Trigger Jenkins"
  status_check:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        uses: joshlk/jenkins-githubaction@master
        id: jenkins
        with:
          url: "http://binarybug-jenkins.centralindia.cloudapp.azure.com:8080/"
          job_name: "piggy_ui_status_check"
          username: "binarybug"
          timeout: "300"
          interval: "30"
          api_token: ${{ secrets.JENKINS_TOKEN }}
          parameters: '{"Branch_Name":"${{github.ref}}"}'
      - name: Get job url
        run: echo "Job url is ${{ steps.jenkins.outputs.build_url }}"
