name: UI Pre Deploy Status Check 🤖👽

on:
  push:
    branches:
      - "!master"
      - "**"
jobs:
  # This workflow contains a job called "Trigger Jenkins"
  status_check:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    steps:
      - name: Split version code
        uses: xom9ikk/split@v1
        id: split
        with:
          string: http://binarybug-jenkins.centralindia.cloudapp.azure.com:8080/job/piggy_ui_pre_deploy_check/44/
          separator: /
          limit: -1
      - name: print number
        run: |
          echo ${{ steps.split.outputs._3 }}
          echo ${{ steps.split.outputs._4 }}
          echo ${{ steps.split.outputs._5 }}
      # - name: Trigger jenkins job
      #   uses: joshlk/jenkins-githubaction@master
      #   id: jenkins
      #   with:
      #     url: "http://binarybug-jenkins.centralindia.cloudapp.azure.com:8080/"
      #     job_name: "piggy_ui_pre_deploy_check"
      #     username: "binarybug"
      #     timeout: "600"
      #     interval: "30"
      #     api_token: ${{ secrets.JENKINS_TOKEN }}
      #     parameters: '{"Branch_Name":"${{github.ref}}",
      #                   "MAJOR":"0",
      #                   "MINOR":"0"}'
      # - name: Get job url
      #   run: echo "Job url is ${{ steps.jenkins.outputs.build_url }}"
