name: Deploy 🚀🚀

on:
  workflow_run:
    workflows: ["UI Master Status Check 🤠"]
    types: [completed]
  workflow_dispatch:
env:
  MAJOR: ${{ vars.MAJOR }}
  MINOR: ${{ vars.MINOR }}
  PATCH: "0"

jobs:
  build:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Update version.json
        run: |
          cd src/configs
          cat version.json
          rm version.json
          echo '{"version": "v${{env.MAJOR}}.${{env.MINOR}}.${{env.PATCH}}"}' > version.json
          cat version.json

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist/piggy-ui/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "piggy-ui"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_04B4641E9ACB4E209B95DC941694EE07 }}
