name: upload version

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
env:
  MAJOR: ${{ vars.MAJOR }}
  MINOR: ${{ vars.MINOR }}
  PATCH: "0"

jobs:
  # This workflow contains a job called "Trigger Jenkins"
  version:
    name: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: change directory to cofig
        run: |
          pwd
          cd src/configs
          ls
          cat version.json
          rm version.json
          ls
          echo 'v${{env.MAJOR}}.${{env.MINOR}}.${{env.PATCH}}' > version.json
          ls
          cat version.json
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-version-app
          path: dist/piggy-ui/browser
